name: 'Sample Dotnet Action'
description: 'sample dotnet based action'
author: 'Your name or organization here'
inputs:
  repository:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  pullRequestNumber:
    required: true
    description: 'input description here'
    default: 'default value if applicable'    
  milliseconds:
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'index.js'