name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Code
      run: ./build.ps1
      shell: pwsh
    - name: Find Current Pull Request
      uses: jwalton/gh-find-current-pr@v1.2.1
    - name: Run Action
      uses: ./
      id: sample
      with:
        repository: ${{github.repository}}
        pullRequestNumber: ${{steps.findPr.outputs.number}}
        ctx: ${{toJSON(github)}}
        milliseconds: 5000