name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Code
      run: ./build.ps1
      shell: pwsh
    - name: Find PR
    - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
    - name: Run Action
      uses: ./
      id: sample
      with:
        repository: ${{github.repository}}
        pullRequestNumber: ${{steps.findPr.outputs.number}}
        ctx: ${{toJSON(github)}}
        milliseconds: 5000